using System.Text.Json.Serialization;

namespace MedicalApp.Models
{
    /// <summary>
    /// Strongly-typed result returned by GPT-4o-mini for a medical analysis PDF.
    /// Mirrors the JSON schema described in the system prompt.
    /// </summary>
    public class InterpretationResult
    {
        [JsonPropertyName("is_medical_analysis")]
        public bool IsMedicalAnalysis { get; set; }

        [JsonPropertyName("rejection_reason")]
        public string? RejectionReason { get; set; }

        [JsonPropertyName("patient_info")]
        public PatientInfo? PatientInfo { get; set; }

        [JsonPropertyName("summary")]
        public string? Summary { get; set; }

        [JsonPropertyName("key_results")]
        public List<KeyResult>? KeyResults { get; set; }

        [JsonPropertyName("abnormal_findings")]
        public List<AbnormalFinding>? AbnormalFindings { get; set; }

        [JsonPropertyName("correlations")]
        public string? Correlations { get; set; }

        [JsonPropertyName("recommendations")]
        public string? Recommendations { get; set; }

        [JsonPropertyName("disclaimer")]
        public string? Disclaimer { get; set; }

        /// <summary>
        /// Lista factorilor de risc generată opțional de Gemini, bazată pe
        /// valorile anormale din PDF + vârsta pacientului. Fiecare element
        /// este o frază naturală în limba interpretării (ex.
        /// „Având LDL=180 mg/dL și HDL=35 mg/dL la 52 ani, există risc
        /// cardiovascular crescut conform scorului Framingham.").
        ///
        /// CARACTERISTICI DE SIGURANȚĂ:
        /// - <c>null</c> și listă vidă sunt valide → secțiunea pur și
        ///   simplu nu se randează (vechi interpretări sau pacienți fără
        ///   anormalități semnificative).
        /// - NU este diagnostic medical; ViewModel-ul afișează un
        ///   disclaimer obligatoriu lângă secțiune.
        /// - Câmp opțional în schema JSON → orice eroare de extracție
        ///   nu afectează restul interpretării (graceful degradation).
        /// </summary>
        [JsonPropertyName("risk_factors")]
        public List<string>? RiskFactors { get; set; }

        /// <summary>
        /// Up to 5 questions the AI suggests the patient asks their doctor at the next
        /// visit. Generated by Gemini from the parameters in THIS PDF (not generic
        /// medicine). Open-ended phrasing, never diagnostic claims.
        ///
        /// CARACTERISTICI DE SIGURANȚĂ:
        /// - <c>null</c> și listă vidă sunt valide → secțiunea pur și
        ///   simplu nu se randează (interpretări vechi din DB sau cazuri rare).
        /// - NU este diagnostic; ViewModel-ul afișează un disclaimer obligatoriu
        ///   sub secțiune, explicând că întrebările sunt sugerate de MedicalApp.
        /// - Câmp opțional în schema JSON → orice eroare de extracție nu
        ///   afectează restul interpretării (graceful degradation).
        /// </summary>
        [JsonPropertyName("doctor_questions")]
        public List<string>? DoctorQuestions { get; set; }

        /// <summary>
        /// Self-audit field added by the model so we can detect silent extraction
        /// gaps. If <see cref="ExtractionAudit.ExpectedCount"/> &gt; the number of
        /// items in <see cref="KeyResults"/>, the model skipped parameters and we
        /// retry the call.
        /// </summary>
        [JsonPropertyName("_extraction_audit")]
        public ExtractionAudit? Audit { get; set; }
    }

    public class ExtractionAudit
    {
        [JsonPropertyName("expected_count")]
        public int ExpectedCount { get; set; }

        [JsonPropertyName("parameter_names")]
        public List<string>? ParameterNames { get; set; }
    }

        public class PatientInfo
        {
            [JsonPropertyName("name")]
            public string? Name { get; set; }

            [JsonPropertyName("age")]
            public string? Age { get; set; }

            [JsonPropertyName("sex")]
            public string? Sex { get; set; }

            [JsonPropertyName("date_taken")]
            public string? DateTaken { get; set; }

            [JsonPropertyName("laboratory")]
            public string? Laboratory { get; set; }

            [JsonPropertyName("doctor_requesting")]
            public string? DoctorRequesting { get; set; }
        }

        public class KeyResult
        {
            [JsonPropertyName("parameter")]
            public string Parameter { get; set; } = string.Empty;

            [JsonPropertyName("value")]
            public string? Value { get; set; }

            [JsonPropertyName("unit")]
            public string? Unit { get; set; }

            [JsonPropertyName("reference_range")]
            public string? ReferenceRange { get; set; }

            /// <summary>normal | high | low | borderline</summary>
            [JsonPropertyName("status")]
            public string Status { get; set; } = "normal";

            [JsonPropertyName("explanation")]
            public string? Explanation { get; set; }

            // -------- Parameter normalization (new pipeline) --------
            // Gemini provides a clean, standardized English medical term for the
            // analyte. A downstream deterministic matcher (Python FastAPI service
            // running semantic + fuzzy + rules search over the local LOINC DB)
            // resolves the actual LOINC code from this normalized name.
            //
            // This separation eliminates LOINC hallucinations at the LLM level:
            // Gemini is good at producing natural-language English medical names
            // and bad at recalling numeric codes; the matcher does the opposite.

            /// <summary>
            /// Standardized English medical term for the analyte, with explicit
            /// specimen, in LOINC-style canonical form, e.g.
            /// "Glucose [Mass/volume] in Serum or Plasma" or
            /// "pH of Urine by Test strip". Null when Gemini cannot map the
            /// parameter to a meaningful English medical term (rare lab-specific
            /// indices, proprietary panels, etc.).
            /// </summary>
            [JsonPropertyName("parameter_normalized_en")]
            public string? ParameterNormalizedEn { get; set; }

            /// <summary>
            /// Textul literal al antetului grupului/panelului din PDF-ul original,
            /// preluat de Gemini fără interpretare (ex. "Hemoleucograma completa -
            /// Sange - Spectroscopie de impedanta, citometrie in flux (PENTRA ES 60)").
            /// Folosit downstream de Python matcher pentru a extrage determinist axele
            /// Sistem și Metodă când Gemini le ratează. Poate fi null când PDF-ul nu
            /// are un antet clar de grup.
            /// </summary>
            [JsonPropertyName("panel_header_raw")]
            public string? PanelHeaderRaw { get; set; }

            // -------- LOINC fields (populated downstream by the matcher) --------
            // These are NOT emitted by Gemini anymore. They are populated by the
            // LoincMatcherClient after the interpretation succeeds, by calling the
            // Python FastAPI matcher service with ParameterNormalizedEn.
            //
            // We kept the property names and JSON attributes identical to the
            // previous pipeline so that:
            //   - archived RawJsonResult records still deserialize correctly,
            //   - PDF re-generation works,
            //   - Compare-by-LOINC grouping (Pas 4) continues to function.

            /// <summary>
            /// Official LOINC code, resolved by the deterministic matcher from
            /// <see cref="ParameterNormalizedEn"/>. Null when no matcher result.
            /// </summary>
            [JsonPropertyName("loinc_code")]
            public string? LoincCode { get; set; }

            /// <summary>
            /// LOINC Long Common Name from the matcher's chosen code. Null when
            /// no match.
            /// </summary>
            [JsonPropertyName("loinc_long_name")]
            public string? LoincLongName { get; set; }

            /// <summary>
            /// Matcher confidence score: "high" (score >= 0.85), "medium"
            /// (0.65 .. 0.85), "low" (&lt; 0.65), null when no match attempted.
            /// </summary>
            [JsonPropertyName("loinc_confidence")]
            public string? LoincConfidence { get; set; }

            /// <summary>
            /// Official LOINC CLASS code (e.g. <c>HEM</c>, <c>CHEM</c>,
            /// <c>SERO</c>, <c>ENDO</c>, <c>COAG</c>, <c>UA</c>) inherited
            /// from the resolved LOINC code's row in the LoincDictionary.
            /// Populated by the Python matcher service. Used by the Compare
            /// view to group parameters by medical specialty
            /// (Hematologie / Biochimie / Imunologie / ...).
            /// Null when the matcher did not find a code, OR when the
            /// resolved code's row in LoincDictionary has no CLASS value.
            /// </summary>
            [JsonPropertyName("loinc_class")]
            public string? LoincClass { get; set; }

            /// <summary>
            /// Provenance of the LOINC mapping. Two values are produced by
            /// the Python matcher:
            /// <list type="bullet">
            ///   <item><c>"anchor"</c> — hard-curated canonical mapping
            ///     (score 1.0, deterministic). Safe to badge in the UI as
            ///     "cod LOINC verificat" — gives the patient confidence
            ///     that common analytes (CBC, lipid panel, liver enzymes)
            ///     are mapped to the exact official LOINC code.</item>
            ///   <item><c>"semantic"</c> — produced by the embedding +
            ///     fuzzy + rules pipeline (probabilistic). Badged in the UI
            ///     as "cod sugerat automat".</item>
            /// </list>
            /// Null only on legacy rows interpreted before this column
            /// was added.
            /// </summary>
            [JsonPropertyName("loinc_source")]
            public string? LoincSource { get; set; }

            /// <summary>
            /// Raw matcher score (0.0 .. 1.0). For <see cref="LoincSource"/> ==
            /// "anchor" this is always 1.0. For "semantic" it reflects the
            /// cosine-similarity + fuzzy-match + rules blend. The UI surfaces
            /// it as a small percentage next to the blue dot, giving the user
            /// an additional confidence signal without overwhelming them.
            /// Null on legacy rows.
            /// </summary>
            [JsonPropertyName("loinc_score")]
            public double? LoincScore { get; set; }
        }

        public class AbnormalFinding
        {
            [JsonPropertyName("parameter")]
            public string Parameter { get; set; } = string.Empty;

            [JsonPropertyName("explanation")]
            public string? Explanation { get; set; }

            /// <summary>mild | moderate | severe</summary>
            [JsonPropertyName("severity")]
            public string Severity { get; set; } = "mild";
        }
    }

