using System.Globalization;

namespace MedicalApp.Services
{
    /// <summary>
    /// Simple in-memory localizer for the MedicalApp.
    /// Use @Loc.T("KeyName") in Razor views or Loc.T("KeyName") in controllers.
    /// </summary>
    public static class Loc
    {
        private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
        {
            ["en"] = new()
            {
                ["AppTitle"] = "MedicalApp",
                ["WelcomeMessage"] = "Welcome in this world",
                ["SelectLanguage"] = "Select language",
                ["Login"] = "Login",
                ["Register"] = "Register",
                ["Email"] = "Email",
                ["Password"] = "Password",
                ["NewPassword"] = "New password",
                ["ConfirmPassword"] = "Confirm Password",
                ["LoginButton"] = "Sign In",
                ["RegisterButton"] = "Create Account",
                ["Logout"] = "Logout",
                ["InvalidCredentials"] = "Invalid email or password.",
                ["EmailAlreadyExists"] = "This email is already registered.",
                ["RegistrationSuccess"] = "Account created successfully. You can now login.",
                ["WelcomeBack"] = "Welcome back",
                ["Credits"] = "Credits",
                ["English"] = "English",
                ["Romanian"] = "Romanian",
                ["French"] = "French",
                ["Spanish"] = "Spanish",
                ["German"] = "German",
                // Validation
                ["PasswordMinLength"] = "Password must be at least {0} characters long.",
                ["PasswordMismatch"] = "The password and confirmation password do not match.",
                ["EmailRequired"] = "Email is required.",
                ["EmailInvalid"] = "Invalid email format.",
                ["PasswordRequired"] = "Password is required.",
                ["ConfirmPasswordRequired"] = "Please confirm your password.",
                // Forgot password (request link)
                ["ForgotPassword"] = "Forgot password?",
                ["ForgotPasswordTitle"] = "Forgot password",
                ["ForgotPasswordIntro"] = "Enter your email address and we will send you a password reset link.",
                ["SendResetLink"] = "Send reset link",
                ["BackToLogin"] = "Back to login",
                ["EmailNotRegistered"] = "This email is not registered in our system.",
                ["ResetLinkSent"] = "A password reset link has been sent to your email. Please check your inbox.",
                ["EmailSendFailed"] = "Failed to send the email. Please try again later.",
                // Reset password (set new password)
                ["ResetPasswordTitle"] = "Reset password",
                ["ResetPasswordIntro"] = "Enter and confirm your new password below.",
                ["ResetPasswordButton"] = "Reset password",
                ["ResetPasswordSuccess"] = "Your password has been reset successfully. You can now log in with the new password.",
                ["InvalidOrExpiredToken"] = "Invalid or expired link",
                ["InvalidOrExpiredTokenIntro"] = "The password reset link is invalid or has expired. Please request a new one.",
                ["RequestNewLink"] = "Request a new link",
                // Email body (reset link)
                ["EmailSubject"] = "Reset your MedicalApp password",
                ["EmailGreeting"] = "Hello,",
                ["EmailResetLinkIntro"] = "You requested to reset your MedicalApp password. Click the button below to choose a new password:",
                ["EmailResetLinkButton"] = "Reset password",
                ["EmailLinkExpiryNote"] = "This link will expire in 30 minutes.",
                ["EmailIgnoreIfNotRequested"] = "If you did not request this, please ignore this email.",
                ["EmailRegards"] = "Regards, MedicalApp Team"
            },
            ["ro"] = new()
            {
                ["AppTitle"] = "MedicalApp",
                ["WelcomeMessage"] = "Bine ai venit în această lume",
                ["SelectLanguage"] = "Selectează limba",
                ["Login"] = "Autentificare",
                ["Register"] = "Înregistrare",
                ["Email"] = "Email",
                ["Password"] = "Parolă",
                ["NewPassword"] = "Parolă nouă",
                ["ConfirmPassword"] = "Confirmă parola",
                ["LoginButton"] = "Autentifică-te",
                ["RegisterButton"] = "Creează cont",
                ["Logout"] = "Deconectare",
                ["InvalidCredentials"] = "Email sau parolă incorecte.",
                ["EmailAlreadyExists"] = "Acest email este deja înregistrat.",
                ["RegistrationSuccess"] = "Cont creat cu succes. Te poți autentifica acum.",
                ["WelcomeBack"] = "Bine ai revenit",
                ["Credits"] = "Credite",
                ["English"] = "Engleză",
                ["Romanian"] = "Română",
                ["French"] = "Franceză",
                ["Spanish"] = "Spaniolă",
                ["German"] = "Germană",
                // Validation
                ["PasswordMinLength"] = "Parola trebuie să aibă cel puțin {0} caractere.",
                ["PasswordMismatch"] = "Parola și confirmarea parolei nu coincid.",
                ["EmailRequired"] = "Email-ul este obligatoriu.",
                ["EmailInvalid"] = "Format email invalid.",
                ["PasswordRequired"] = "Parola este obligatorie.",
                ["ConfirmPasswordRequired"] = "Te rugăm să confirmi parola.",
                // Forgot password
                ["ForgotPassword"] = "Ai uitat parola?",
                ["ForgotPasswordTitle"] = "Recuperare parolă",
                ["ForgotPasswordIntro"] = "Introdu adresa de email și îți vom trimite un link pentru resetarea parolei.",
                ["SendResetLink"] = "Trimite link de resetare",
                ["BackToLogin"] = "Înapoi la autentificare",
                ["EmailNotRegistered"] = "Acest email nu este înregistrat în sistem.",
                ["ResetLinkSent"] = "Un link pentru resetarea parolei a fost trimis pe email. Verifică inbox-ul.",
                ["EmailSendFailed"] = "Trimiterea email-ului a eșuat. Te rugăm să încerci mai târziu.",
                // Reset password
                ["ResetPasswordTitle"] = "Resetare parolă",
                ["ResetPasswordIntro"] = "Introdu și confirmă noua ta parolă mai jos.",
                ["ResetPasswordButton"] = "Resetează parola",
                ["ResetPasswordSuccess"] = "Parola a fost resetată cu succes. Te poți autentifica acum cu noua parolă.",
                ["InvalidOrExpiredToken"] = "Link invalid sau expirat",
                ["InvalidOrExpiredTokenIntro"] = "Link-ul de resetare este invalid sau a expirat. Te rugăm să soliciți unul nou.",
                ["RequestNewLink"] = "Solicită un link nou",
                // Email body
                ["EmailSubject"] = "Resetare parolă MedicalApp",
                ["EmailGreeting"] = "Salut,",
                ["EmailResetLinkIntro"] = "Ai solicitat resetarea parolei pentru contul tău MedicalApp. Apasă butonul de mai jos pentru a alege o parolă nouă:",
                ["EmailResetLinkButton"] = "Resetează parola",
                ["EmailLinkExpiryNote"] = "Acest link expiră în 30 de minute.",
                ["EmailIgnoreIfNotRequested"] = "Dacă nu ai solicitat acest lucru, te rugăm să ignori acest email.",
                ["EmailRegards"] = "Cu respect, Echipa MedicalApp"
            },
            ["fr"] = new()
            {
                ["AppTitle"] = "MedicalApp",
                ["WelcomeMessage"] = "Bienvenue dans ce monde",
                ["SelectLanguage"] = "Choisir la langue",
                ["Login"] = "Connexion",
                ["Register"] = "S'inscrire",
                ["Email"] = "Email",
                ["Password"] = "Mot de passe",
                ["NewPassword"] = "Nouveau mot de passe",
                ["ConfirmPassword"] = "Confirmer le mot de passe",
                ["LoginButton"] = "Se connecter",
                ["RegisterButton"] = "Créer un compte",
                ["Logout"] = "Déconnexion",
                ["InvalidCredentials"] = "Email ou mot de passe invalide.",
                ["EmailAlreadyExists"] = "Cet email est déjà enregistré.",
                ["RegistrationSuccess"] = "Compte créé avec succès. Vous pouvez vous connecter.",
                ["WelcomeBack"] = "Bon retour",
                ["Credits"] = "Crédits",
                ["English"] = "Anglais",
                ["Romanian"] = "Roumain",
                ["French"] = "Français",
                ["Spanish"] = "Espagnol",
                ["German"] = "Allemand",
                // Validation
                ["PasswordMinLength"] = "Le mot de passe doit contenir au moins {0} caractères.",
                ["PasswordMismatch"] = "Le mot de passe et la confirmation ne correspondent pas.",
                ["EmailRequired"] = "L'email est obligatoire.",
                ["EmailInvalid"] = "Format d'email invalide.",
                ["PasswordRequired"] = "Le mot de passe est obligatoire.",
                ["ConfirmPasswordRequired"] = "Veuillez confirmer votre mot de passe.",
                // Forgot password
                ["ForgotPassword"] = "Mot de passe oublié ?",
                ["ForgotPasswordTitle"] = "Mot de passe oublié",
                ["ForgotPasswordIntro"] = "Entrez votre adresse email et nous vous enverrons un lien de réinitialisation du mot de passe.",
                ["SendResetLink"] = "Envoyer le lien de réinitialisation",
                ["BackToLogin"] = "Retour à la connexion",
                ["EmailNotRegistered"] = "Cet email n'est pas enregistré dans notre système.",
                ["ResetLinkSent"] = "Un lien de réinitialisation du mot de passe a été envoyé à votre email. Veuillez vérifier votre boîte de réception.",
                ["EmailSendFailed"] = "L'envoi de l'email a échoué. Veuillez réessayer plus tard.",
                // Reset password
                ["ResetPasswordTitle"] = "Réinitialiser le mot de passe",
                ["ResetPasswordIntro"] = "Saisissez et confirmez votre nouveau mot de passe ci-dessous.",
                ["ResetPasswordButton"] = "Réinitialiser le mot de passe",
                ["ResetPasswordSuccess"] = "Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter avec le nouveau mot de passe.",
                ["InvalidOrExpiredToken"] = "Lien invalide ou expiré",
                ["InvalidOrExpiredTokenIntro"] = "Le lien de réinitialisation est invalide ou a expiré. Veuillez en demander un nouveau.",
                ["RequestNewLink"] = "Demander un nouveau lien",
                // Email body
                ["EmailSubject"] = "Réinitialiser votre mot de passe MedicalApp",
                ["EmailGreeting"] = "Bonjour,",
                ["EmailResetLinkIntro"] = "Vous avez demandé la réinitialisation de votre mot de passe MedicalApp. Cliquez sur le bouton ci-dessous pour choisir un nouveau mot de passe :",
                ["EmailResetLinkButton"] = "Réinitialiser le mot de passe",
                ["EmailLinkExpiryNote"] = "Ce lien expirera dans 30 minutes.",
                ["EmailIgnoreIfNotRequested"] = "Si vous n'avez pas demandé cela, veuillez ignorer cet email.",
                ["EmailRegards"] = "Cordialement, L'équipe MedicalApp"
            },
            ["es"] = new()
            {
                ["AppTitle"] = "MedicalApp",
                ["WelcomeMessage"] = "Bienvenido a este mundo",
                ["SelectLanguage"] = "Seleccionar idioma",
                ["Login"] = "Iniciar sesión",
                ["Register"] = "Registrarse",
                ["Email"] = "Correo",
                ["Password"] = "Contraseña",
                ["NewPassword"] = "Nueva contraseña",
                ["ConfirmPassword"] = "Confirmar contraseña",
                ["LoginButton"] = "Entrar",
                ["RegisterButton"] = "Crear cuenta",
                ["Logout"] = "Cerrar sesión",
                ["InvalidCredentials"] = "Correo o contraseña inválidos.",
                ["EmailAlreadyExists"] = "Este correo ya está registrado.",
                ["RegistrationSuccess"] = "Cuenta creada con éxito. Ya puede iniciar sesión.",
                ["WelcomeBack"] = "Bienvenido de nuevo",
                ["Credits"] = "Créditos",
                ["English"] = "Inglés",
                ["Romanian"] = "Rumano",
                ["French"] = "Francés",
                ["Spanish"] = "Español",
                ["German"] = "Alemán",
                // Validation
                ["PasswordMinLength"] = "La contraseña debe tener al menos {0} caracteres.",
                ["PasswordMismatch"] = "La contraseña y la confirmación no coinciden.",
                ["EmailRequired"] = "El correo es obligatorio.",
                ["EmailInvalid"] = "Formato de correo inválido.",
                ["PasswordRequired"] = "La contraseña es obligatoria.",
                ["ConfirmPasswordRequired"] = "Por favor confirme su contraseña.",
                // Forgot password
                ["ForgotPassword"] = "¿Olvidó su contraseña?",
                ["ForgotPasswordTitle"] = "Contraseña olvidada",
                ["ForgotPasswordIntro"] = "Introduzca su correo y le enviaremos un enlace para restablecer la contraseña.",
                ["SendResetLink"] = "Enviar enlace de restablecimiento",
                ["BackToLogin"] = "Volver al inicio de sesión",
                ["EmailNotRegistered"] = "Este correo no está registrado en nuestro sistema.",
                ["ResetLinkSent"] = "Se ha enviado un enlace de restablecimiento a su correo. Por favor, revise su bandeja de entrada.",
                ["EmailSendFailed"] = "Error al enviar el correo. Por favor, inténtelo más tarde.",
                // Reset password
                ["ResetPasswordTitle"] = "Restablecer contraseña",
                ["ResetPasswordIntro"] = "Introduzca y confirme su nueva contraseña abajo.",
                ["ResetPasswordButton"] = "Restablecer contraseña",
                ["ResetPasswordSuccess"] = "Su contraseña se ha restablecido con éxito. Ya puede iniciar sesión con la nueva contraseña.",
                ["InvalidOrExpiredToken"] = "Enlace inválido o expirado",
                ["InvalidOrExpiredTokenIntro"] = "El enlace de restablecimiento no es válido o ha expirado. Por favor, solicite uno nuevo.",
                ["RequestNewLink"] = "Solicitar un nuevo enlace",
                // Email body
                ["EmailSubject"] = "Restablecer contraseña de MedicalApp",
                ["EmailGreeting"] = "Hola,",
                ["EmailResetLinkIntro"] = "Ha solicitado restablecer su contraseña de MedicalApp. Haga clic en el botón de abajo para elegir una nueva contraseña:",
                ["EmailResetLinkButton"] = "Restablecer contraseña",
                ["EmailLinkExpiryNote"] = "Este enlace expirará en 30 minutos.",
                ["EmailIgnoreIfNotRequested"] = "Si no solicitó esto, por favor ignore este correo.",
                ["EmailRegards"] = "Saludos, Equipo MedicalApp"
            },
            ["de"] = new()
            {
                ["AppTitle"] = "MedicalApp",
                ["WelcomeMessage"] = "Willkommen in dieser Welt",
                ["SelectLanguage"] = "Sprache auswählen",
                ["Login"] = "Anmelden",
                ["Register"] = "Registrieren",
                ["Email"] = "E-Mail",
                ["Password"] = "Passwort",
                ["NewPassword"] = "Neues Passwort",
                ["ConfirmPassword"] = "Passwort bestätigen",
                ["LoginButton"] = "Einloggen",
                ["RegisterButton"] = "Konto erstellen",
                ["Logout"] = "Abmelden",
                ["InvalidCredentials"] = "Ungültige E-Mail oder Passwort.",
                ["EmailAlreadyExists"] = "Diese E-Mail ist bereits registriert.",
                ["RegistrationSuccess"] = "Konto erfolgreich erstellt. Sie können sich jetzt anmelden.",
                ["WelcomeBack"] = "Willkommen zurück",
                ["Credits"] = "Credits",
                ["English"] = "Englisch",
                ["Romanian"] = "Rumänisch",
                ["French"] = "Französisch",
                ["Spanish"] = "Spanisch",
                ["German"] = "Deutsch",
                // Validation
                ["PasswordMinLength"] = "Das Passwort muss mindestens {0} Zeichen lang sein.",
                ["PasswordMismatch"] = "Passwort und Bestätigung stimmen nicht überein.",
                ["EmailRequired"] = "E-Mail ist erforderlich.",
                ["EmailInvalid"] = "Ungültiges E-Mail-Format.",
                ["PasswordRequired"] = "Passwort ist erforderlich.",
                ["ConfirmPasswordRequired"] = "Bitte bestätigen Sie Ihr Passwort.",
                // Forgot password
                ["ForgotPassword"] = "Passwort vergessen?",
                ["ForgotPasswordTitle"] = "Passwort vergessen",
                ["ForgotPasswordIntro"] = "Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen des Passworts.",
                ["SendResetLink"] = "Reset-Link senden",
                ["BackToLogin"] = "Zurück zur Anmeldung",
                ["EmailNotRegistered"] = "Diese E-Mail ist in unserem System nicht registriert.",
                ["ResetLinkSent"] = "Ein Link zum Zurücksetzen des Passworts wurde an Ihre E-Mail gesendet. Bitte überprüfen Sie Ihren Posteingang.",
                ["EmailSendFailed"] = "Das Senden der E-Mail ist fehlgeschlagen. Bitte versuchen Sie es später erneut.",
                // Reset password
                ["ResetPasswordTitle"] = "Passwort zurücksetzen",
                ["ResetPasswordIntro"] = "Geben Sie Ihr neues Passwort unten ein und bestätigen Sie es.",
                ["ResetPasswordButton"] = "Passwort zurücksetzen",
                ["ResetPasswordSuccess"] = "Ihr Passwort wurde erfolgreich zurückgesetzt. Sie können sich jetzt mit dem neuen Passwort anmelden.",
                ["InvalidOrExpiredToken"] = "Ungültiger oder abgelaufener Link",
                ["InvalidOrExpiredTokenIntro"] = "Der Link zum Zurücksetzen des Passworts ist ungültig oder abgelaufen. Bitte fordern Sie einen neuen an.",
                ["RequestNewLink"] = "Neuen Link anfordern",
                // Email body
                ["EmailSubject"] = "MedicalApp Passwort zurücksetzen",
                ["EmailGreeting"] = "Hallo,",
                ["EmailResetLinkIntro"] = "Sie haben angefordert, Ihr MedicalApp-Passwort zurückzusetzen. Klicken Sie auf die Schaltfläche unten, um ein neues Passwort zu wählen:",
                ["EmailResetLinkButton"] = "Passwort zurücksetzen",
                ["EmailLinkExpiryNote"] = "Dieser Link läuft in 30 Minuten ab.",
                ["EmailIgnoreIfNotRequested"] = "Wenn Sie dies nicht angefordert haben, ignorieren Sie bitte diese E-Mail.",
                ["EmailRegards"] = "Mit freundlichen Grüßen, das MedicalApp-Team"
            }
        };

        public static string T(string key)
        {
            var culture = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
            if (_translations.TryGetValue(culture, out var dict) && dict.TryGetValue(key, out var val))
                return val;
            if (_translations["en"].TryGetValue(key, out var fallback))
                return fallback;
            return key;
        }
    }
}
